apiVersion: v1
kind: Pod
metadata:
  name: multitool-single-pod
  labels:
    app: multitool-single-pod
spec:
  containers:
    - name: multitool
      image: wbitt/network-multitool
      ports:
        - containerPort: 80