apiVersion: v1
kind: Service
metadata:
  name: netology-network-lesson-nodeport-1-4
spec:
  selector:
    app: nginx-with-multitool
  ports:
    - name: nginx
      protocol: TCP
      port: 9001
      targetPort: 80
      nodePort: 31000
    - name: multitool
      protocol: TCP
      port: 9002
      targetPort: 8080
      nodePort: 31001
  type: NodePort