apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multi
spec:
  selector:
    matchLabels:
      app: multi
  template:
    metadata:
      labels:
        app: multi
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
        - name: varlog
          mountPath: /var/log/hostlogs
      volumes:
      - name: varlog
        hostPath:
          path: /var/log