apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  index.html: |
    - Test
    - Netology
  nginx.conf: |
    events {}
    http {
        server {
            listen 80;
            listen 443 ssl;
            ssl_certificate /etc/nginx/ssl/tls.crt;
            ssl_certificate_key /etc/nginx/ssl/tls.key;

            location / {
                root /usr/share/nginx/html;
                index index.html;
            }
        }
    }
